### ISSUE TITLE
Closures

### ISSUE THREAD

**Issue by Simn** [waneck/haxe-genc#5]
and all the contextual binding that comes with them.

**Comment by waneck** [comment]
Higher-order functions will really be really hard to do it right.
The biggest problem is that we can't simply make a struct with the function and its context, as we intend to use only fully typed functions (e.g. no `value`-only functions, like we have in neko)

One solution would be to generate, along with the function, a dynamic variant of it:

```
static function add(x:Int, y:Int):Int
{
    return x + y;
}

var add1:Int->Int->Int = add;
var add2:Dynamic->Int->Int = add;
var add3:Int->Dynamic->Dynamic = add;
```

would be translated into

```
int add(int x, int y)
{
    return x + y;
}
```

but also the dynamic variant:

```
Dynamic *add_dyn(void *this, int nargs,...)
{
    va_args args;
    if (nargs != 2) hx_throw("invalid arguments");
    va_start(args, nargs * 2);
    type *t1 = va_arg(args, type*);
    type *t2 = va_arg(args, type*);
    int x = t1->to_int_args(&args);
    int y = t2->to_int_args(&args);

    return int_type->box(add(x,y));
}
```

which can be called like this:

```
typedef Dynamic *dynamic_function(void *this, int nargs, ...);

struct function
{
    Dynamic *this;
    dynamic_function *func;
}

call it like:

function *myfunc;

myfunc->func(myfunc->this, 2, int_type, int_type, 3, 4);
```

I'm not sure if function pointers to variable arguments are part of the standard, but I think they are.
The "_dyn" variant of functions is close to how hxcpp deals with them. I know it's a lot of code for each function, so we may find a better way to deal with them. As hinted by the starting example, the issue is that we can call "add" with Dynamics instead of the Int->Int->Int form.
I'd also like to avoid having a solution that would e.g. depend on libffi, since some platforms do not allow JIT compilation (e.g. ios), and it becomes very hard to debug code written like this

**Comment by waneck** [comment]
edit: I've made add_dyn call add() instead of inlining the contents again

**Comment by Simn** [comment]
This is currently not working:

```
class Main {
    static public function main() {
        var s0 = "foo";
        function assign(s1) {
            s0 = s1;
        }
        assign("bar");
        trace(s0); // foo
    }
}
```

The generated closure assigns to the ctx field:

```
void Main__hx_func_0(c__hx_anon_1* _ctx,String* s1){
    (_ctx)->s0 = s1;
}
```

**Comment by Simn** [comment]
Ignore me, I thought I had changed the capture policy, but apparently I hadn't.

**Comment by Simn** [comment]
I think we can close this. I'm sure there are some issues remaining, but the basic implementation is done and works nicely.
